import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import QRCode from "qrcode";
import { Child, DashboardStats, Defaulter } from "@/types/child";

// Ghana Health Service branding colors
const GHS_GREEN: [number, number, number] = [0, 100, 0];
const GHS_GOLD: [number, number, number] = [255, 215, 0];
const GHS_RED: [number, number, number] = [206, 17, 38];
const GHS_DARK: [number, number, number] = [30, 41, 59];

interface PDFOptions {
  facilityName?: string;
  reportDate?: string;
}

function addHeader(doc: jsPDF, title: string, options: PDFOptions = {}) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const { facilityName = "Health Facility", reportDate = new Date().toLocaleDateString() } = options;

  // Green header bar
  doc.setFillColor(...GHS_GREEN);
  doc.rect(0, 0, pageWidth, 35, "F");

  // Gold accent line
  doc.setFillColor(...GHS_GOLD);
  doc.rect(0, 35, pageWidth, 3, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Ghana Health Service", 14, 15);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Immunization Tracker - 2030 EPI Agenda", 14, 23);

  // Facility info on right
  doc.setFontSize(10);
  doc.text(facilityName, pageWidth - 14, 15, { align: "right" });
  doc.text(`Report Date: ${reportDate}`, pageWidth - 14, 23, { align: "right" });

  // Report title
  doc.setTextColor(...GHS_DARK);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 50);

  return 55; // Return Y position after header
}

function addFooter(doc: jsPDF, pageNumber: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Footer line
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(0.5);
  doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);

  // Footer text
  doc.setTextColor(...GHS_DARK);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Ghana Health Service - No Child Left Behind", 14, pageHeight - 8);
  doc.text(`Page ${pageNumber}`, pageWidth - 14, pageHeight - 8, { align: "right" });
  doc.text("Generated by Immunization Tracker", pageWidth / 2, pageHeight - 8, { align: "center" });
}

export function exportSummaryReport(
  stats: DashboardStats,
  ageDistribution: Record<string, number>,
  period: string,
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  let yPos = addHeader(doc, "Summary Report", options);

  // Period info
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GHS_DARK);
  doc.text(`Reporting Period: ${period.charAt(0).toUpperCase() + period.slice(1)}`, 14, yPos);
  yPos += 10;

  // Stats table
  autoTable(doc, {
    startY: yPos,
    head: [["Metric", "Value"]],
    body: [
      ["Total Children Registered", stats.totalChildren.toString()],
      ["Fully Immunized", stats.fullyImmunized.toString()],
      ["Vaccinated Today", stats.vaccinatedToday.toString()],
      ["Due This Week", stats.dueSoon.toString()],
      ["Defaulters", stats.defaulters.toString()],
      ["Coverage Rate", `${stats.coverageRate}%`],
      ["Dropout Rate", `${stats.dropoutRate}%`],
    ],
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 100 },
      1: { halign: "right", cellWidth: 50 },
    },
    margin: { left: 14, right: 14 },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 80;
  yPos += 15;

  // Age Distribution
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Age Distribution", 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Age Group", "Children", "Percentage"]],
    body: Object.entries(ageDistribution).map(([group, count]) => {
      const total = Object.values(ageDistribution).reduce((a, b) => a + b, 0);
      const percent = total > 0 ? Math.round((count / total) * 100) : 0;
      return [group, count.toString(), `${percent}%`];
    }),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, 1);
  doc.save(`GHS_Summary_Report_${new Date().toISOString().split("T")[0]}.pdf`);
}

export function exportDetailedReport(
  records: Array<{
    date: string;
    childName: string;
    regNo: string;
    vaccine: string;
    batchNumber: string;
    status: string;
  }>,
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  let yPos = addHeader(doc, "Detailed Vaccination Records", options);

  doc.setFontSize(11);
  doc.setTextColor(...GHS_DARK);
  doc.text(`Total Records: ${records.length}`, 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Date", "Reg No.", "Child Name", "Vaccine", "Batch No.", "Status"]],
    body: records.map((r) => [
      new Date(r.date).toLocaleDateString(),
      r.regNo,
      r.childName,
      r.vaccine,
      r.batchNumber,
      r.status,
    ]),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 8,
      cellPadding: 4,
    },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 30 },
      2: { cellWidth: 40 },
      3: { cellWidth: 50 },
      4: { cellWidth: 25 },
      5: { cellWidth: 20 },
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber);
    },
  });

  doc.save(`GHS_Detailed_Report_${new Date().toISOString().split("T")[0]}.pdf`);
}

export function exportVaccineCoverageReport(
  vaccineCoverage: Record<string, { given: number; pending: number; overdue: number }>,
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  let yPos = addHeader(doc, "Vaccine Coverage Report", options);

  autoTable(doc, {
    startY: yPos,
    head: [["Vaccine Type", "Given", "Pending", "Overdue", "Total", "Coverage %"]],
    body: Object.entries(vaccineCoverage).map(([type, data]) => {
      const total = data.given + data.pending + data.overdue;
      const coverage = total > 0 ? Math.round((data.given / total) * 100) : 0;
      return [
        type,
        data.given.toString(),
        data.pending.toString(),
        data.overdue.toString(),
        total.toString(),
        `${coverage}%`,
      ];
    }),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 45 },
      1: { halign: "center", cellWidth: 25 },
      2: { halign: "center", cellWidth: 25 },
      3: { halign: "center", cellWidth: 25 },
      4: { halign: "center", cellWidth: 25 },
      5: { halign: "center", cellWidth: 30, fontStyle: "bold" },
    },
    margin: { left: 14, right: 14 },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 100;
  yPos += 15;

  // Legend
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Legend:", 14, yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  // Given indicator
  doc.setFillColor(0, 100, 0);
  doc.circle(18, yPos - 1, 2, "F");
  doc.text("Given - Vaccines successfully administered", 24, yPos);
  yPos += 6;

  // Pending indicator
  doc.setFillColor(245, 158, 11);
  doc.circle(18, yPos - 1, 2, "F");
  doc.text("Pending - Vaccines not yet due or awaiting administration", 24, yPos);
  yPos += 6;

  // Overdue indicator
  doc.setFillColor(206, 17, 38);
  doc.circle(18, yPos - 1, 2, "F");
  doc.text("Overdue - Vaccines past due date requiring follow-up", 24, yPos);

  addFooter(doc, 1);
  doc.save(`GHS_Vaccine_Coverage_${new Date().toISOString().split("T")[0]}.pdf`);
}

export function exportDefaultersReport(
  defaulters: Defaulter[],
  options: PDFOptions = {}
) {
  const doc = new jsPDF("landscape");
  let yPos = addHeader(doc, "Defaulters Report", options);

  // Summary stats
  const critical = defaulters.filter((d) => d.daysOverdue > 30).length;
  const moderate = defaulters.filter((d) => d.daysOverdue >= 14 && d.daysOverdue <= 30).length;
  const recent = defaulters.filter((d) => d.daysOverdue < 14).length;

  doc.setFontSize(10);
  doc.setTextColor(...GHS_DARK);
  doc.text(`Total Defaulters: ${defaulters.length}`, 14, yPos);
  
  doc.setTextColor(206, 17, 38);
  doc.text(`Critical (>30 days): ${critical}`, 80, yPos);
  
  doc.setTextColor(245, 158, 11);
  doc.text(`Moderate (14-30 days): ${moderate}`, 150, yPos);
  
  doc.setTextColor(59, 130, 246);
  doc.text(`Recent (<14 days): ${recent}`, 230, yPos);
  
  yPos += 10;

  autoTable(doc, {
    startY: yPos,
    head: [["#", "Child Name", "Mother", "Contact", "Community", "Missed Vaccines", "Due Date", "Days Overdue"]],
    body: defaulters.map((d, idx) => [
      (idx + 1).toString(),
      d.child.name,
      d.child.motherName,
      d.child.telephoneAddress || "N/A",
      d.child.community || "N/A",
      d.missedVaccines.slice(0, 2).join(", ") + (d.missedVaccines.length > 2 ? ` +${d.missedVaccines.length - 2}` : ""),
      new Date(d.dueDate).toLocaleDateString(),
      d.daysOverdue.toString(),
    ]),
    headStyles: {
      fillColor: GHS_RED,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [255, 235, 238],
    },
    styles: {
      fontSize: 8,
      cellPadding: 4,
    },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      1: { cellWidth: 35 },
      2: { cellWidth: 35 },
      3: { cellWidth: 35 },
      4: { cellWidth: 30 },
      5: { cellWidth: 60 },
      6: { cellWidth: 25 },
      7: { cellWidth: 25, halign: "center" },
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber);
    },
    // Color code rows by severity
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 7) {
        const daysOverdue = parseInt(data.cell.raw as string);
        if (daysOverdue > 30) {
          data.cell.styles.textColor = [206, 17, 38];
          data.cell.styles.fontStyle = "bold";
        } else if (daysOverdue >= 14) {
          data.cell.styles.textColor = [245, 158, 11];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });

  doc.save(`GHS_Defaulters_Report_${new Date().toISOString().split("T")[0]}.pdf`);
}

export function exportChildrenRegister(
  children: Child[],
  options: PDFOptions = {}
) {
  const doc = new jsPDF("landscape");
  let yPos = addHeader(doc, "Child Health Register", options);

  doc.setFontSize(10);
  doc.setTextColor(...GHS_DARK);
  doc.text(`Total Children (0-59 months): ${children.length}`, 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Reg No.", "Name", "DOB", "Age", "Sex", "Mother", "Contact", "Community", "Vaccines"]],
    body: children.map((child) => {
      const birthDate = new Date(child.dateOfBirth);
      const today = new Date();
      const months = (today.getFullYear() - birthDate.getFullYear()) * 12 + (today.getMonth() - birthDate.getMonth());
      const completed = child.vaccines.filter((v) => v.status === "completed").length;
      const total = child.vaccines.length;
      
      return [
        child.regNo,
        child.name,
        new Date(child.dateOfBirth).toLocaleDateString(),
        `${months}m`,
        child.sex,
        child.motherName,
        child.telephoneAddress || "N/A",
        child.community || "N/A",
        `${completed}/${total}`,
      ];
    }),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber);
    },
  });

  doc.save(`GHS_Children_Register_${new Date().toISOString().split("T")[0]}.pdf`);
}

export async function exportImmunizationCard(
  child: Child,
  options: PDFOptions = {}
) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: [148, 210], // A5 size for card
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const { facilityName = "Health Facility" } = options;

  // Generate QR code with child data
  const qrData = JSON.stringify({
    id: child.id,
    regNo: child.regNo,
    name: child.name,
    dob: child.dateOfBirth,
    facility: facilityName,
  });
  
  const qrCodeDataUrl = await QRCode.toDataURL(qrData, {
    width: 200,
    margin: 1,
    color: {
      dark: "#006400",
      light: "#ffffff",
    },
  });

  // Card border
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(1.5);
  doc.rect(4, 4, pageWidth - 8, 202, "S");

  // Header
  doc.setFillColor(...GHS_GREEN);
  doc.rect(4, 4, pageWidth - 8, 22, "F");
  
  // Gold accent
  doc.setFillColor(...GHS_GOLD);
  doc.rect(4, 26, pageWidth - 8, 2, "F");

  // Header text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("GHANA HEALTH SERVICE", pageWidth / 2, 12, { align: "center" });
  
  doc.setFontSize(11);
  doc.text("Child Health Record Card", pageWidth / 2, 19, { align: "center" });
  
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Expanded Programme on Immunization", pageWidth / 2, 24, { align: "center" });

  // Child info section
  let yPos = 34;
  doc.setTextColor(...GHS_DARK);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("CHILD INFORMATION", 10, yPos);
  yPos += 6;

  // QR Code on the right
  doc.addImage(qrCodeDataUrl, "PNG", pageWidth - 40, 32, 32, 32);

  // Child details
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const details = [
    ["Reg. No:", child.regNo],
    ["Name:", child.name],
    ["Date of Birth:", new Date(child.dateOfBirth).toLocaleDateString()],
    ["Sex:", child.sex],
    ["Mother's Name:", child.motherName],
    ["Contact:", child.telephoneAddress],
    ["Community:", child.community],
  ];

  details.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 10, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(value || "N/A", 38, yPos);
    yPos += 5;
  });

  yPos += 5;

  // Vaccination schedule header
  doc.setFillColor(232, 245, 232);
  doc.rect(10, yPos, pageWidth - 20, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("VACCINATION SCHEDULE", 12, yPos + 5);
  yPos += 10;

  // Group vaccines by age
  const vaccineGroups: Record<string, typeof child.vaccines> = {};
  child.vaccines.forEach((vaccine) => {
    const agePart = vaccine.name.includes("at") ? vaccine.name.split("at")[1].trim() : "Other";
    if (!vaccineGroups[agePart]) {
      vaccineGroups[agePart] = [];
    }
    vaccineGroups[agePart].push(vaccine);
  });

  // Vaccination table
  autoTable(doc, {
    startY: yPos,
    head: [["Vaccine", "Due Date", "Given Date", "Batch No.", "✓"]],
    body: child.vaccines.slice(0, 18).map((v) => [
      v.name.split(" at")[0],
      new Date(v.dueDate).toLocaleDateString(),
      v.givenDate ? new Date(v.givenDate).toLocaleDateString() : "-",
      v.batchNumber || "-",
      v.status === "completed" ? "✓" : "",
    ]),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontSize: 7,
      cellPadding: 1.5,
    },
    bodyStyles: {
      fontSize: 6.5,
      cellPadding: 1.2,
    },
    alternateRowStyles: {
      fillColor: [245, 250, 245],
    },
    columnStyles: {
      0: { cellWidth: 35 },
      1: { cellWidth: 22 },
      2: { cellWidth: 22 },
      3: { cellWidth: 20 },
      4: { cellWidth: 8, halign: "center" },
    },
    margin: { left: 10, right: 10 },
    tableWidth: pageWidth - 20,
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 4 && data.cell.raw === "✓") {
        data.cell.styles.textColor = [0, 100, 0];
        data.cell.styles.fontStyle = "bold";
      }
    },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 80;

  // Footer section
  if (yPos < 180) {
    yPos = 180;
  }

  doc.setDrawColor(...GHS_GOLD);
  doc.setLineWidth(0.5);
  doc.line(10, yPos, pageWidth - 10, yPos);
  yPos += 5;

  doc.setFontSize(7);
  doc.setTextColor(...GHS_DARK);
  doc.setFont("helvetica", "italic");
  doc.text("This card should be brought to every clinic visit.", pageWidth / 2, yPos, { align: "center" });
  yPos += 4;
  doc.text("If lost, please report to your nearest health facility.", pageWidth / 2, yPos, { align: "center" });
  yPos += 6;

  // Facility stamp area
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.text("Facility Stamp:", 10, yPos);
  doc.setDrawColor(...GHS_DARK);
  doc.setLineDashPattern([1, 1], 0);
  doc.rect(10, yPos + 2, 40, 15, "S");

  // Signature area
  doc.text("Health Worker Signature:", pageWidth - 50, yPos);
  doc.line(pageWidth - 50, yPos + 10, pageWidth - 10, yPos + 10);

  doc.save(`GHS_Immunization_Card_${child.regNo}_${child.name.replace(/\s+/g, "_")}.pdf`);
}
