import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import QRCode from "qrcode";
import { Child, DashboardStats, Defaulter } from "@/types/child";

// Ghana Health Service branding colors
const GHS_GREEN: [number, number, number] = [0, 100, 0];
const GHS_GOLD: [number, number, number] = [255, 215, 0];
const GHS_RED: [number, number, number] = [206, 17, 38];
const GHS_DARK: [number, number, number] = [30, 41, 59];

interface PDFOptions {
  facilityName?: string;
  reportDate?: string;
  periodLabel?: string;
}

// Format date as DD/MM/YYYY
export function formatDateDDMMYYYY(date: Date | string): string {
  const d = typeof date === 'string' ? new Date(date) : date;
  const day = String(d.getDate()).padStart(2, '0');
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const year = d.getFullYear();
  return `${day}/${month}/${year}`;
}

// Helper to create safe filename
function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9-_]/g, '_').substring(0, 50);
}

function addHeader(doc: jsPDF, title: string, options: PDFOptions = {}) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const { 
    facilityName = "Health Facility", 
    reportDate = formatDateDDMMYYYY(new Date()),
    periodLabel 
  } = options;

  // Green header bar
  doc.setFillColor(...GHS_GREEN);
  doc.rect(0, 0, pageWidth, 40, "F");

  // Gold accent line
  doc.setFillColor(...GHS_GOLD);
  doc.rect(0, 40, pageWidth, 3, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Ghana Health Service", 14, 15);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Immunization Tracker - 2030 EPI Agenda", 14, 23);

  // Facility info on right
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(facilityName, pageWidth - 14, 12, { align: "right" });
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Report Date: ${reportDate}`, pageWidth - 14, 20, { align: "right" });
  
  if (periodLabel) {
    doc.text(`Period: ${periodLabel}`, pageWidth - 14, 28, { align: "right" });
  }

  // Report title
  doc.setTextColor(...GHS_DARK);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 55);

  return 62; // Return Y position after header
}

function addFooter(doc: jsPDF, pageNumber: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Footer line
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(0.5);
  doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);

  // Footer text
  doc.setTextColor(...GHS_DARK);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Ghana Health Service - No Child Left Behind", 14, pageHeight - 8);
  doc.text(`Page ${pageNumber}`, pageWidth - 14, pageHeight - 8, { align: "right" });
  doc.text("Generated by Immunization Tracker", pageWidth / 2, pageHeight - 8, { align: "center" });
}

export function exportSummaryReport(
  stats: DashboardStats,
  ageDistribution: Record<string, number>,
  period: string,
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  let yPos = addHeader(doc, "Summary Report", options);

  // Period info
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GHS_DARK);
  doc.text(`Reporting Period: ${period.charAt(0).toUpperCase() + period.slice(1)}`, 14, yPos);
  yPos += 10;

  // Stats table
  autoTable(doc, {
    startY: yPos,
    head: [["Metric", "Value"]],
    body: [
      ["Total Children Registered", stats.totalChildren.toString()],
      ["Fully Immunized", stats.fullyImmunized.toString()],
      ["Vaccinated Today", stats.vaccinatedToday.toString()],
      ["Due This Week", stats.dueSoon.toString()],
      ["Defaulters", stats.defaulters.toString()],
      ["Coverage Rate", `${stats.coverageRate}%`],
      ["Dropout Rate", `${stats.dropoutRate}%`],
    ],
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 100 },
      1: { halign: "right", cellWidth: 50 },
    },
    margin: { left: 14, right: 14 },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 80;
  yPos += 15;

  // Age Distribution
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Age Distribution", 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Age Group", "Children", "Percentage"]],
    body: Object.entries(ageDistribution).map(([group, count]) => {
      const total = Object.values(ageDistribution).reduce((a, b) => a + b, 0);
      const percent = total > 0 ? Math.round((count / total) * 100) : 0;
      return [group, count.toString(), `${percent}%`];
    }),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, 1);
  
  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const periodSlug = options.periodLabel ? `_${sanitizeFilename(options.periodLabel)}` : '';
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Summary_Report${periodSlug}_${dateSlug}.pdf`);
}

export function exportDetailedReport(
  records: Array<{
    date: string;
    childName: string;
    regNo: string;
    vaccine: string;
    batchNumber: string;
    status: string;
  }>,
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  let yPos = addHeader(doc, "Detailed Vaccination Records", options);

  doc.setFontSize(11);
  doc.setTextColor(...GHS_DARK);
  doc.text(`Total Records: ${records.length}`, 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Date", "Reg No.", "Child Name", "Vaccine", "Batch No.", "Status"]],
    body: records.map((r) => [
      formatDateDDMMYYYY(r.date),
      r.regNo,
      r.childName,
      r.vaccine,
      r.batchNumber,
      r.status,
    ]),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 8,
      cellPadding: 4,
    },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 30 },
      2: { cellWidth: 40 },
      3: { cellWidth: 50 },
      4: { cellWidth: 25 },
      5: { cellWidth: 20 },
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber);
    },
  });

  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const periodSlug = options.periodLabel ? `_${sanitizeFilename(options.periodLabel)}` : '';
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Detailed_Report${periodSlug}_${dateSlug}.pdf`);
}

export function exportVaccineCoverageReport(
  vaccineCoverage: Record<string, { given: number; pending: number; overdue: number }>,
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  let yPos = addHeader(doc, "Vaccine Coverage Report", options);

  autoTable(doc, {
    startY: yPos,
    head: [["Vaccine Type", "Given", "Pending", "Overdue", "Total", "Coverage %"]],
    body: Object.entries(vaccineCoverage).map(([type, data]) => {
      const total = data.given + data.pending + data.overdue;
      const coverage = total > 0 ? Math.round((data.given / total) * 100) : 0;
      return [
        type,
        data.given.toString(),
        data.pending.toString(),
        data.overdue.toString(),
        total.toString(),
        `${coverage}%`,
      ];
    }),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 45 },
      1: { halign: "center", cellWidth: 25 },
      2: { halign: "center", cellWidth: 25 },
      3: { halign: "center", cellWidth: 25 },
      4: { halign: "center", cellWidth: 25 },
      5: { halign: "center", cellWidth: 30, fontStyle: "bold" },
    },
    margin: { left: 14, right: 14 },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 100;
  yPos += 15;

  // Legend
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Legend:", 14, yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  // Given indicator
  doc.setFillColor(0, 100, 0);
  doc.circle(18, yPos - 1, 2, "F");
  doc.text("Given - Vaccines successfully administered", 24, yPos);
  yPos += 6;

  // Pending indicator
  doc.setFillColor(245, 158, 11);
  doc.circle(18, yPos - 1, 2, "F");
  doc.text("Pending - Vaccines not yet due or awaiting administration", 24, yPos);
  yPos += 6;

  // Overdue indicator
  doc.setFillColor(206, 17, 38);
  doc.circle(18, yPos - 1, 2, "F");
  doc.text("Overdue - Vaccines past due date requiring follow-up", 24, yPos);

  addFooter(doc, 1);
  
  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const periodSlug = options.periodLabel ? `_${sanitizeFilename(options.periodLabel)}` : '';
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Vaccine_Coverage${periodSlug}_${dateSlug}.pdf`);
}

export function exportDefaultersReport(
  defaulters: Defaulter[],
  options: PDFOptions = {}
) {
  const doc = new jsPDF("landscape");
  let yPos = addHeader(doc, "Defaulters Report", options);

  // Summary stats
  const critical = defaulters.filter((d) => d.daysOverdue > 30).length;
  const moderate = defaulters.filter((d) => d.daysOverdue >= 14 && d.daysOverdue <= 30).length;
  const recent = defaulters.filter((d) => d.daysOverdue < 14).length;

  doc.setFontSize(10);
  doc.setTextColor(...GHS_DARK);
  doc.text(`Total Defaulters: ${defaulters.length}`, 14, yPos);
  
  doc.setTextColor(206, 17, 38);
  doc.text(`Critical (>30 days): ${critical}`, 80, yPos);
  
  doc.setTextColor(245, 158, 11);
  doc.text(`Moderate (14-30 days): ${moderate}`, 150, yPos);
  
  doc.setTextColor(59, 130, 246);
  doc.text(`Recent (<14 days): ${recent}`, 230, yPos);
  
  yPos += 10;

  autoTable(doc, {
    startY: yPos,
    head: [["#", "Child Name", "Mother", "Contact", "Community", "Missed Vaccines", "Due Date", "Days Overdue"]],
    body: defaulters.map((d, idx) => [
      (idx + 1).toString(),
      d.child.name,
      d.child.motherName,
      d.child.telephoneAddress || "N/A",
      d.child.community || "N/A",
      d.missedVaccines.slice(0, 2).join(", ") + (d.missedVaccines.length > 2 ? ` +${d.missedVaccines.length - 2}` : ""),
      formatDateDDMMYYYY(d.dueDate),
      d.daysOverdue.toString(),
    ]),
    headStyles: {
      fillColor: GHS_RED,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [255, 235, 238],
    },
    styles: {
      fontSize: 8,
      cellPadding: 4,
    },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      1: { cellWidth: 35 },
      2: { cellWidth: 35 },
      3: { cellWidth: 35 },
      4: { cellWidth: 30 },
      5: { cellWidth: 60 },
      6: { cellWidth: 25 },
      7: { cellWidth: 25, halign: "center" },
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber);
    },
    // Color code rows by severity
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 7) {
        const daysOverdue = parseInt(data.cell.raw as string);
        if (daysOverdue > 30) {
          data.cell.styles.textColor = [206, 17, 38];
          data.cell.styles.fontStyle = "bold";
        } else if (daysOverdue >= 14) {
          data.cell.styles.textColor = [245, 158, 11];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });

  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const periodSlug = options.periodLabel ? `_${sanitizeFilename(options.periodLabel)}` : '';
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Defaulters_Report${periodSlug}_${dateSlug}.pdf`);
}

export function exportChildrenRegister(
  children: Child[],
  options: PDFOptions = {}
) {
  const doc = new jsPDF("landscape");
  let yPos = addHeader(doc, "Child Health Register", options);

  doc.setFontSize(10);
  doc.setTextColor(...GHS_DARK);
  doc.text(`Total Children (0-59 months): ${children.length}`, 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Reg No.", "Name", "DOB", "Age", "Sex", "Mother", "Contact", "Community", "Vaccines"]],
    body: children.map((child) => {
      const birthDate = new Date(child.dateOfBirth);
      const today = new Date();
      const months = (today.getFullYear() - birthDate.getFullYear()) * 12 + (today.getMonth() - birthDate.getMonth());
      const completed = child.vaccines.filter((v) => v.status === "completed").length;
      const total = child.vaccines.length;
      
      return [
        child.regNo,
        child.name,
        formatDateDDMMYYYY(child.dateOfBirth),
        `${months}m`,
        child.sex,
        child.motherName,
        child.telephoneAddress || "N/A",
        child.community || "N/A",
        `${completed}/${total}`,
      ];
    }),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber);
    },
  });

  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Children_Register_${dateSlug}.pdf`);
}

// Export individual child's vaccine history with administered vaccines
export function exportVaccineHistory(
  child: Child,
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  let yPos = addHeader(doc, "Vaccination History Report", options);

  // Child info
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_DARK);
  doc.text("Child Information", 14, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const birthDate = new Date(child.dateOfBirth);
  const today = new Date();
  const months = (today.getFullYear() - birthDate.getFullYear()) * 12 + (today.getMonth() - birthDate.getMonth());
  
  const childInfo = [
    ["Registration No:", child.regNo],
    ["Name:", child.name],
    ["Date of Birth:", formatDateDDMMYYYY(child.dateOfBirth)],
    ["Age:", `${months} months`],
    ["Sex:", child.sex],
    ["Mother's Name:", child.motherName],
    ["Contact:", child.telephoneAddress || "N/A"],
    ["Community:", child.community || "N/A"],
  ];

  childInfo.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 14, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(value, 55, yPos);
    yPos += 6;
  });

  yPos += 10;

  // Filter administered vaccines
  const administeredVaccines = child.vaccines.filter(v => v.status === "completed" && v.givenDate);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Administered Vaccines (${administeredVaccines.length})`, 14, yPos);
  yPos += 8;

  if (administeredVaccines.length === 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(150, 150, 150);
    doc.text("No vaccines have been administered yet.", 14, yPos);
  } else {
    autoTable(doc, {
      startY: yPos,
      head: [["#", "Vaccine", "Date Given", "Batch Number", "Administered By"]],
      body: administeredVaccines.map((v, idx) => [
        (idx + 1).toString(),
        v.name,
        v.givenDate ? formatDateDDMMYYYY(v.givenDate) : "N/A",
        v.batchNumber || "N/A",
        v.administeredBy || "N/A",
      ]),
      headStyles: {
        fillColor: GHS_GREEN,
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 9,
      },
      alternateRowStyles: {
        fillColor: [232, 245, 232],
      },
      styles: {
        fontSize: 8,
        cellPadding: 4,
      },
      columnStyles: {
        0: { cellWidth: 10, halign: "center" },
        1: { cellWidth: 70 },
        2: { cellWidth: 30 },
        3: { cellWidth: 30 },
        4: { cellWidth: 40 },
      },
      margin: { left: 14, right: 14 },
    });

    yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 50;
  }

  // Summary stats
  yPos += 15;
  const completed = child.vaccines.filter(v => v.status === "completed").length;
  const pending = child.vaccines.filter(v => v.status === "pending").length;
  const overdue = child.vaccines.filter(v => v.status === "overdue").length;
  const total = child.vaccines.length;
  const progress = total > 0 ? Math.round((completed / total) * 100) : 0;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Vaccination Summary", 14, yPos);
  yPos += 8;

  // Progress bar
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(14, yPos, 100, 8, 2, 2, "F");
  doc.setFillColor(...GHS_GREEN);
  doc.roundedRect(14, yPos, progress, 8, 2, 2, "F");
  doc.setFontSize(9);
  doc.setTextColor(...GHS_DARK);
  doc.text(`${progress}% Complete`, 120, yPos + 6);
  yPos += 15;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setFillColor(...GHS_GREEN);
  doc.circle(18, yPos - 1, 2, "F");
  doc.text(`Completed: ${completed}`, 24, yPos);
  
  doc.setFillColor(245, 158, 11);
  doc.circle(70, yPos - 1, 2, "F");
  doc.text(`Pending: ${pending}`, 76, yPos);
  
  doc.setFillColor(...GHS_RED);
  doc.circle(120, yPos - 1, 2, "F");
  doc.text(`Overdue: ${overdue}`, 126, yPos);

  addFooter(doc, 1);
  
  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Vaccine_History_${child.regNo}_${dateSlug}.pdf`);
}

export async function exportImmunizationCard(
  child: Child,
  options: PDFOptions = {}
) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: [148, 210], // A5 size for card
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const { facilityName = "Health Facility" } = options;

  // Generate QR code with verification data
  const verificationData = {
    id: child.id,
    regNo: child.regNo,
    name: child.name,
    dob: child.dateOfBirth,
    sex: child.sex,
    facility: facilityName,
    vaccinesCompleted: child.vaccines.filter(v => v.status === "completed").length,
    totalVaccines: child.vaccines.length,
    generatedAt: new Date().toISOString(),
  };
  
  const qrCodeDataUrl = await QRCode.toDataURL(JSON.stringify(verificationData), {
    width: 300,
    margin: 1,
    errorCorrectionLevel: 'H',
    color: {
      dark: "#006400",
      light: "#ffffff",
    },
  });

  // Border
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(1.5);
  doc.rect(4, 4, pageWidth - 8, pageHeight - 8, "S");

  // Header
  doc.setFillColor(...GHS_GREEN);
  doc.rect(4, 4, pageWidth - 8, 22, "F");
  
  // Gold accent line
  doc.setFillColor(...GHS_GOLD);
  doc.rect(4, 26, pageWidth - 8, 2, "F");

  // Header text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("REPUBLIC OF GHANA", pageWidth / 2, 10, { align: "center" });
  
  doc.setFontSize(12);
  doc.text("GHANA HEALTH SERVICE", pageWidth / 2, 16, { align: "center" });
  
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Child Immunization Record Card", pageWidth / 2, 22, { align: "center" });

  // Facility name - prominent
  let yPos = 34;
  doc.setFillColor(...GHS_GREEN);
  doc.rect(8, yPos - 3, pageWidth - 16, 10, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(facilityName.toUpperCase(), pageWidth / 2, yPos + 4, { align: "center" });

  // Child info section
  yPos = 48;
  doc.setTextColor(...GHS_DARK);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("CHILD DETAILS", 10, yPos);
  
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(0.3);
  doc.line(10, yPos + 1, 80, yPos + 1);
  yPos += 5;

  // QR Code
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(0.5);
  doc.addImage(qrCodeDataUrl, "PNG", pageWidth - 40, 44, 30, 30);
  doc.setFontSize(5);
  doc.setTextColor(100, 100, 100);
  doc.text("Scan to Verify", pageWidth - 25, 76, { align: "center" });

  // Child details
  doc.setFontSize(7);
  doc.setTextColor(...GHS_DARK);
  const details: [string, string][] = [
    ["Reg No:", child.regNo],
    ["Name:", child.name],
    ["DOB:", formatDateDDMMYYYY(child.dateOfBirth)],
    ["Sex:", child.sex],
    ["Caregiver:", child.motherName],
    ["Contact:", child.telephoneAddress || "N/A"],
  ];

  details.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 10, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(String(value).substring(0, 25), 28, yPos);
    yPos += 4;
  });

  yPos += 2;

  // Immunization record header
  doc.setFillColor(...GHS_GREEN);
  doc.rect(8, yPos, pageWidth - 16, 7, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("IMMUNIZATION RECORD", pageWidth / 2, yPos + 5, { align: "center" });
  yPos += 10;

  // Calculate statistics
  const completed = child.vaccines.filter(v => v.status === "completed").length;
  const total = child.vaccines.length;
  const progress = total > 0 ? Math.round((completed / total) * 100) : 0;

  // Vaccination table - compact
  autoTable(doc, {
    startY: yPos,
    head: [["Vaccine", "Due", "Given", "✓"]],
    body: child.vaccines.slice(0, 18).map((v) => [
      v.name.split(" at")[0].substring(0, 20),
      new Date(v.dueDate).toLocaleDateString('en-GB', { day: '2-digit', month: '2-digit', year: '2-digit' }),
      v.givenDate ? new Date(v.givenDate).toLocaleDateString('en-GB', { day: '2-digit', month: '2-digit', year: '2-digit' }) : "-",
      v.status === "completed" ? "✓" : v.status === "overdue" ? "!" : "○",
    ]),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontSize: 6,
      cellPadding: 1,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 5.5,
      cellPadding: 0.8,
    },
    alternateRowStyles: {
      fillColor: [245, 250, 245],
    },
    columnStyles: {
      0: { cellWidth: 35 },
      1: { cellWidth: 22 },
      2: { cellWidth: 22 },
      3: { cellWidth: 10, halign: "center", fontStyle: "bold" },
    },
    margin: { left: 8, right: 8 },
    tableWidth: pageWidth - 16,
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 3) {
        if (data.cell.raw === "✓") {
          data.cell.styles.textColor = [0, 100, 0];
        } else if (data.cell.raw === "!") {
          data.cell.styles.textColor = [206, 17, 38];
        } else {
          data.cell.styles.textColor = [150, 150, 150];
        }
      }
    },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 80;
  yPos += 4;

  // Progress bar
  doc.setFillColor(245, 250, 245);
  doc.roundedRect(8, yPos, pageWidth - 16, 10, 2, 2, "F");
  
  doc.setFontSize(6);
  doc.setTextColor(...GHS_DARK);
  doc.setFont("helvetica", "bold");
  doc.text("PROGRESS:", 12, yPos + 4);
  
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(35, yPos + 2, 50, 4, 1, 1, "F");
  doc.setFillColor(...GHS_GREEN);
  doc.roundedRect(35, yPos + 2, (progress / 100) * 50, 4, 1, 1, "F");
  
  doc.setFontSize(8);
  doc.text(`${progress}%`, 88, yPos + 5);
  
  doc.setFontSize(5);
  doc.setFont("helvetica", "normal");
  doc.text(`${completed}/${total} vaccines completed`, 100, yPos + 5);

  // Footer
  yPos = pageHeight - 20;
  doc.setFillColor(...GHS_GOLD);
  doc.rect(8, yPos, pageWidth - 16, 1, "F");
  yPos += 4;

  doc.setFontSize(5);
  doc.setTextColor(...GHS_DARK);
  doc.text("This card is an official health document. Bring it to every clinic visit.", pageWidth / 2, yPos, { align: "center" });
  
  // Bottom bar
  doc.setFillColor(...GHS_GREEN);
  doc.rect(4, pageHeight - 6, pageWidth - 8, 2, "F");
  
  doc.setFontSize(4);
  doc.setTextColor(100, 100, 100);
  doc.text(`ID: ${child.regNo} | Generated: ${formatDateDDMMYYYY(new Date())} | Ghana Health Service`, pageWidth / 2, pageHeight - 3, { align: "center" });

  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  doc.save(`${facilitySlug}_Immunization_Card_${child.regNo}_${child.name.replace(/\s+/g, "_")}.pdf`);
}

// Export outreach session report for bulk vaccination
export interface OutreachVaccinationRecord {
  childId: string;
  childName: string;
  regNo: string;
  motherName: string;
  community?: string;
  vaccine: string;
  dateGiven: string;
  batchNumber: string;
}

export function exportOutreachSessionReport(
  records: OutreachVaccinationRecord[],
  sessionDetails: {
    vaccineName: string;
    sessionDate: string;
    batchNumber: string;
    totalChildren: number;
    totalMales?: number;
    totalFemales?: number;
  },
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  const { facilityName = "Health Facility" } = options;
  let yPos = addHeader(doc, "Outreach Session Report", options);

  // Facility Name
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_GREEN);
  doc.text(facilityName, 14, yPos);
  yPos += 10;

  // Session Summary
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_DARK);
  doc.text("Session Summary", 14, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  
  const sessionInfo: [string, string][] = [
    ["Vaccine Administered:", sessionDetails.vaccineName],
    ["Session Date:", formatDateDDMMYYYY(sessionDetails.sessionDate)],
    ["Batch Number:", sessionDetails.batchNumber],
    ["Total Children Vaccinated:", sessionDetails.totalChildren.toString()],
  ];

  // Add gender breakdown if available
  if (sessionDetails.totalMales !== undefined && sessionDetails.totalFemales !== undefined) {
    sessionInfo.push(["Total Males:", sessionDetails.totalMales.toString()]);
    sessionInfo.push(["Total Females:", sessionDetails.totalFemales.toString()]);
  }

  sessionInfo.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 14, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(value, 65, yPos);
    yPos += 6;
  });

  yPos += 10;

  // Vaccination Records Table
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Vaccinated Children", 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["#", "Reg No.", "Child Name", "Mother's Name", "Community", "Date Given", "Batch No."]],
    body: records.map((r, idx) => [
      (idx + 1).toString(),
      r.regNo,
      r.childName,
      r.motherName,
      r.community || "N/A",
      formatDateDDMMYYYY(r.dateGiven),
      r.batchNumber,
    ]),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 8,
      cellPadding: 4,
    },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      1: { cellWidth: 28 },
      2: { cellWidth: 35 },
      3: { cellWidth: 35 },
      4: { cellWidth: 30 },
      5: { cellWidth: 25 },
      6: { cellWidth: 25 },
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber);
    },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 80;
  yPos += 15;

  // Signature section
  if (yPos < doc.internal.pageSize.getHeight() - 60) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GHS_DARK);
    
    doc.text("Prepared By:", 14, yPos);
    doc.line(45, yPos, 100, yPos);
    
    doc.text("Signature:", 110, yPos);
    doc.line(135, yPos, 180, yPos);
    
    yPos += 10;
    
    doc.text("Date:", 14, yPos);
    doc.line(30, yPos, 70, yPos);
    
    doc.text("Facility Stamp:", 110, yPos);
    doc.setDrawColor(...GHS_DARK);
    doc.setLineDashPattern([1, 1], 0);
    doc.rect(150, yPos - 15, 35, 25, "S");
  }

  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const vaccineSlug = sanitizeFilename(sessionDetails.vaccineName);
  const dateSlug = new Date(sessionDetails.sessionDate).toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Outreach_Session_${vaccineSlug}_${dateSlug}.pdf`);
}

// Export consolidated report combining all report types for a date range
export function exportConsolidatedReport(
  data: {
    stats: DashboardStats;
    ageDistribution: Record<string, number>;
    detailedRecords: Array<{
      date: string;
      childName: string;
      regNo: string;
      vaccine: string;
      batchNumber: string;
      status: string;
    }>;
    vaccineCoverage: Record<string, { given: number; pending: number; overdue: number; eligible?: number }>;
    defaulters: Defaulter[];
  },
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  const { facilityName = "Health Facility", periodLabel } = options;
  let currentPage = 1;
  
  // ============ Page 1: Summary Report ============
  let yPos = addHeader(doc, "Consolidated Report - Summary", options);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GHS_DARK);
  doc.text(`Reporting Period: ${periodLabel || 'All Time'}`, 14, yPos);
  yPos += 10;

  // Stats table
  autoTable(doc, {
    startY: yPos,
    head: [["Metric", "Value"]],
    body: [
      ["Total Children Registered", data.stats.totalChildren.toString()],
      ["Fully Immunized", data.stats.fullyImmunized.toString()],
      ["Vaccinated Today", data.stats.vaccinatedToday.toString()],
      ["Due This Week", data.stats.dueSoon.toString()],
      ["Defaulters", data.stats.defaulters.toString()],
      ["Coverage Rate", `${data.stats.coverageRate}%`],
      ["Dropout Rate", `${data.stats.dropoutRate}%`],
    ],
    headStyles: { fillColor: GHS_GREEN, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [232, 245, 232] },
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 100 }, 1: { halign: "right", cellWidth: 50 } },
    margin: { left: 14, right: 14 },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 80;
  yPos += 15;

  // Age Distribution
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Age Distribution", 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Age Group", "Children", "Percentage"]],
    body: Object.entries(data.ageDistribution).map(([group, count]) => {
      const total = Object.values(data.ageDistribution).reduce((a, b) => a + b, 0);
      const percent = total > 0 ? Math.round((count / total) * 100) : 0;
      return [group, count.toString(), `${percent}%`];
    }),
    headStyles: { fillColor: GHS_GREEN, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [232, 245, 232] },
    styles: { fontSize: 10, cellPadding: 5 },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, currentPage);
  currentPage++;

  // ============ Page 2: Vaccine Coverage ============
  doc.addPage();
  yPos = addHeader(doc, "Consolidated Report - Vaccine Coverage", options);

  autoTable(doc, {
    startY: yPos,
    head: [["Schedule", "Eligible", "Given", "Pending", "Overdue", "Coverage %"]],
    body: Object.entries(data.vaccineCoverage).map(([type, coverage]) => {
      const eligible = coverage.eligible || (coverage.given + coverage.pending + coverage.overdue);
      const coveragePercent = eligible > 0 ? Math.round((coverage.given / eligible) * 100) : 0;
      return [type, eligible.toString(), coverage.given.toString(), coverage.pending.toString(), coverage.overdue.toString(), `${coveragePercent}%`];
    }),
    headStyles: { fillColor: GHS_GREEN, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [232, 245, 232] },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 40 }, 5: { fontStyle: "bold", halign: "center" } },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, currentPage);
  currentPage++;

  // ============ Page 3+: Detailed Records ============
  doc.addPage();
  yPos = addHeader(doc, "Consolidated Report - Detailed Records", options);

  doc.setFontSize(11);
  doc.setTextColor(...GHS_DARK);
  doc.text(`Total Records: ${data.detailedRecords.length}`, 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Date", "Reg No.", "Child Name", "Vaccine", "Batch No.", "Status"]],
    body: data.detailedRecords.slice(0, 100).map((r) => [
      formatDateDDMMYYYY(r.date),
      r.regNo,
      r.childName,
      r.vaccine,
      r.batchNumber,
      r.status,
    ]),
    headStyles: { fillColor: GHS_GREEN, textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 },
    alternateRowStyles: { fillColor: [232, 245, 232] },
    styles: { fontSize: 8, cellPadding: 4 },
    margin: { left: 14, right: 14 },
    didDrawPage: (pageData) => { addFooter(doc, currentPage + pageData.pageNumber - 1); },
  });

  // ============ Defaulters Page ============
  if (data.defaulters.length > 0) {
    doc.addPage();
    yPos = addHeader(doc, "Consolidated Report - Defaulters", options);

    const critical = data.defaulters.filter((d) => d.daysOverdue > 30).length;
    const moderate = data.defaulters.filter((d) => d.daysOverdue >= 14 && d.daysOverdue <= 30).length;
    const recent = data.defaulters.filter((d) => d.daysOverdue < 14).length;

    doc.setFontSize(10);
    doc.setTextColor(...GHS_DARK);
    doc.text(`Total Defaulters: ${data.defaulters.length}  |  Critical (>30d): ${critical}  |  Moderate (14-30d): ${moderate}  |  Recent (<14d): ${recent}`, 14, yPos);
    yPos += 10;

    autoTable(doc, {
      startY: yPos,
      head: [["#", "Child Name", "Mother", "Missed Vaccines", "Due Date", "Days Overdue"]],
      body: data.defaulters.slice(0, 50).map((d, idx) => [
        (idx + 1).toString(),
        d.child.name,
        d.child.motherName,
        d.missedVaccines.slice(0, 2).join(", ") + (d.missedVaccines.length > 2 ? ` +${d.missedVaccines.length - 2}` : ""),
        formatDateDDMMYYYY(d.dueDate),
        d.daysOverdue.toString(),
      ]),
      headStyles: { fillColor: GHS_RED, textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 },
      alternateRowStyles: { fillColor: [255, 235, 238] },
      styles: { fontSize: 8, cellPadding: 4 },
      margin: { left: 14, right: 14 },
      didDrawPage: (pageData) => { addFooter(doc, pageData.pageNumber); },
    });
  }

  const facilitySlug = sanitizeFilename(facilityName);
  const periodSlug = periodLabel ? `_${sanitizeFilename(periodLabel)}` : '';
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Consolidated_Report${periodSlug}_${dateSlug}.pdf`);
}

// Export month comparison report
export function exportMonthComparisonReport(
  comparisonData: {
    month1: { periodLabel: string; uniqueChildren: number; totalVaccinations: number; defaulters: number };
    month2: { periodLabel: string; uniqueChildren: number; totalVaccinations: number; defaulters: number };
  },
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  const { facilityName = "Health Facility" } = options;
  
  const yPosStart = addHeader(doc, "Month-to-Month Comparison Report", {
    ...options,
    periodLabel: `${comparisonData.month1.periodLabel} vs ${comparisonData.month2.periodLabel}`
  });
  let yPos = yPosStart;

  // Comparison header
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_DARK);
  doc.text("Side-by-Side Comparison", 14, yPos);
  yPos += 10;

  const pageWidth = doc.internal.pageSize.getWidth();
  const halfWidth = (pageWidth - 42) / 2;

  // Month 1 Box
  doc.setFillColor(232, 245, 232);
  doc.roundedRect(14, yPos, halfWidth, 60, 3, 3, "F");
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(0.5);
  doc.roundedRect(14, yPos, halfWidth, 60, 3, 3, "S");

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_GREEN);
  doc.text(comparisonData.month1.periodLabel, 20, yPos + 12);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GHS_DARK);
  doc.text(`Unique Children: ${comparisonData.month1.uniqueChildren}`, 20, yPos + 26);
  doc.text(`Total Vaccinations: ${comparisonData.month1.totalVaccinations}`, 20, yPos + 38);
  doc.text(`Defaulters: ${comparisonData.month1.defaulters}`, 20, yPos + 50);

  // Month 2 Box
  const month2X = 14 + halfWidth + 14;
  doc.setFillColor(232, 245, 232);
  doc.roundedRect(month2X, yPos, halfWidth, 60, 3, 3, "F");
  doc.setDrawColor(...GHS_GREEN);
  doc.roundedRect(month2X, yPos, halfWidth, 60, 3, 3, "S");

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_GREEN);
  doc.text(comparisonData.month2.periodLabel, month2X + 6, yPos + 12);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GHS_DARK);
  doc.text(`Unique Children: ${comparisonData.month2.uniqueChildren}`, month2X + 6, yPos + 26);
  doc.text(`Total Vaccinations: ${comparisonData.month2.totalVaccinations}`, month2X + 6, yPos + 38);
  doc.text(`Defaulters: ${comparisonData.month2.defaulters}`, month2X + 6, yPos + 50);

  yPos += 75;

  // Change Analysis Section
  doc.setFillColor(...GHS_GOLD);
  doc.rect(14, yPos, pageWidth - 28, 8, "F");
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_DARK);
  doc.text("CHANGE ANALYSIS", 18, yPos + 6);
  yPos += 15;

  const childrenDiff = comparisonData.month1.uniqueChildren - comparisonData.month2.uniqueChildren;
  const vaccDiff = comparisonData.month1.totalVaccinations - comparisonData.month2.totalVaccinations;
  const defaulterDiff = comparisonData.month1.defaulters - comparisonData.month2.defaulters;

  const changes = [
    { metric: "Children Seen", diff: childrenDiff, positive: childrenDiff > 0 },
    { metric: "Vaccinations Given", diff: vaccDiff, positive: vaccDiff > 0 },
    { metric: "Defaulters", diff: defaulterDiff, positive: defaulterDiff < 0 }, // fewer defaulters is good
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["Metric", `${comparisonData.month1.periodLabel}`, `${comparisonData.month2.periodLabel}`, "Change", "Trend"]],
    body: [
      ["Children Seen", comparisonData.month1.uniqueChildren.toString(), comparisonData.month2.uniqueChildren.toString(), 
       `${childrenDiff > 0 ? '+' : ''}${childrenDiff}`, childrenDiff > 0 ? "↑ Increase" : childrenDiff < 0 ? "↓ Decrease" : "→ No Change"],
      ["Vaccinations", comparisonData.month1.totalVaccinations.toString(), comparisonData.month2.totalVaccinations.toString(),
       `${vaccDiff > 0 ? '+' : ''}${vaccDiff}`, vaccDiff > 0 ? "↑ Increase" : vaccDiff < 0 ? "↓ Decrease" : "→ No Change"],
      ["Defaulters", comparisonData.month1.defaulters.toString(), comparisonData.month2.defaulters.toString(),
       `${defaulterDiff > 0 ? '+' : ''}${defaulterDiff}`, defaulterDiff < 0 ? "↑ Improved" : defaulterDiff > 0 ? "↓ Worsened" : "→ No Change"],
    ],
    headStyles: { fillColor: GHS_GREEN, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [232, 245, 232] },
    styles: { fontSize: 10, cellPadding: 6 },
    columnStyles: { 
      0: { fontStyle: "bold" },
      3: { halign: "center", fontStyle: "bold" },
      4: { halign: "center" }
    },
    margin: { left: 14, right: 14 },
    didParseCell: (cellData) => {
      if (cellData.section === "body" && cellData.column.index === 4) {
        const text = cellData.cell.raw as string;
        if (text.includes("Increase") || text.includes("Improved")) {
          cellData.cell.styles.textColor = [0, 128, 0];
        } else if (text.includes("Decrease") || text.includes("Worsened")) {
          cellData.cell.styles.textColor = [206, 17, 38];
        }
      }
      if (cellData.section === "body" && cellData.column.index === 3) {
        const text = cellData.cell.raw as string;
        if (text.startsWith('+')) {
          cellData.cell.styles.textColor = [0, 128, 0];
        } else if (text.startsWith('-')) {
          cellData.cell.styles.textColor = [206, 17, 38];
        }
      }
    },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 60;
  yPos += 20;

  // Summary recommendation
  doc.setFillColor(250, 250, 240);
  doc.roundedRect(14, yPos, pageWidth - 28, 35, 3, 3, "F");
  doc.setDrawColor(...GHS_GOLD);
  doc.roundedRect(14, yPos, pageWidth - 28, 35, 3, 3, "S");

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_DARK);
  doc.text("Summary:", 20, yPos + 10);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const summaryText = `Comparing ${comparisonData.month1.periodLabel} to ${comparisonData.month2.periodLabel}: ` +
    `${Math.abs(childrenDiff)} ${childrenDiff >= 0 ? 'more' : 'fewer'} children seen, ` +
    `${Math.abs(vaccDiff)} ${vaccDiff >= 0 ? 'more' : 'fewer'} vaccinations administered, ` +
    `${Math.abs(defaulterDiff)} ${defaulterDiff <= 0 ? 'fewer' : 'more'} defaulters.`;
  
  const splitText = doc.splitTextToSize(summaryText, pageWidth - 50);
  doc.text(splitText, 20, yPos + 20);

  addFooter(doc, 1);

  const facilitySlug = sanitizeFilename(facilityName);
  const month1Slug = sanitizeFilename(comparisonData.month1.periodLabel);
  const month2Slug = sanitizeFilename(comparisonData.month2.periodLabel);
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Comparison_${month1Slug}_vs_${month2Slug}_${dateSlug}.pdf`);
}
