import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import QRCode from "qrcode";
import { Child, DashboardStats, Defaulter } from "@/types/child";
import { FACILITY_CONFIG } from "@/lib/facilityConfig";
import ghsLogoUrl from "@/assets/ghs-logo.png";
import { buildCompleteScheduleRows } from "@/lib/certificateExport";

// Ghana Health Service branding colors
const GHS_GREEN: [number, number, number] = [0, 100, 0];
const GHS_GOLD: [number, number, number] = [255, 215, 0];
const GHS_RED: [number, number, number] = [206, 17, 38];
const GHS_DARK: [number, number, number] = [30, 41, 59];

// Helper to load GHS logo as base64 for PDF embedding
async function loadGHSLogoBase64(): Promise<string | null> {
  try {
    const response = await fetch(ghsLogoUrl);
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

interface PDFOptions {
  facilityName?: string;
  reportDate?: string;
  periodLabel?: string;
}

// Format date as DD/MM/YYYY
export function formatDateDDMMYYYY(date: Date | string): string {
  const d = typeof date === 'string' ? new Date(date) : date;
  const day = String(d.getDate()).padStart(2, '0');
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const year = d.getFullYear();
  return `${day}/${month}/${year}`;
}

// Helper to create safe filename
function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9-_]/g, '_').substring(0, 50);
}

function addHeader(doc: jsPDF, title: string, options: PDFOptions = {}) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const facilityName = options.facilityName || FACILITY_CONFIG.name;
  const reportDate = options.reportDate || formatDateDDMMYYYY(new Date());
  const periodLabel = options.periodLabel;
  const district = FACILITY_CONFIG.district;

  // Green header bar
  doc.setFillColor(...GHS_GREEN);
  doc.rect(0, 0, pageWidth, 44, "F");

  // Gold accent line
  doc.setFillColor(...GHS_GOLD);
  doc.rect(0, 44, pageWidth, 3, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Ghana Health Service", 14, 15);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Immunization Tracker - 2030 EPI Agenda", 14, 23);

  // Facility info on right
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(facilityName, pageWidth - 14, 12, { align: "right" });
  
  // District info
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(district, pageWidth - 14, 19, { align: "right" });
  
  doc.setFontSize(9);
  doc.text(`Report Date: ${reportDate}`, pageWidth - 14, 27, { align: "right" });
  
  if (periodLabel) {
    doc.text(`Period: ${periodLabel}`, pageWidth - 14, 35, { align: "right" });
  }

  // Report title
  doc.setTextColor(...GHS_DARK);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 59);

  return 66; // Return Y position after header
}

function addFooter(doc: jsPDF, pageNumber: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Footer line
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(0.5);
  doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);

  // Footer text
  doc.setTextColor(...GHS_DARK);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Ghana Health Service - No Child Left Behind", 14, pageHeight - 8);
  doc.text(`Page ${pageNumber}`, pageWidth - 14, pageHeight - 8, { align: "right" });
  doc.text("Generated by Immunization Tracker", pageWidth / 2, pageHeight - 8, { align: "center" });
}

export function exportSummaryReport(
  stats: DashboardStats,
  ageDistribution: Record<string, number>,
  period: string,
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  let yPos = addHeader(doc, "Summary Report", options);

  // Period info
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GHS_DARK);
  doc.text(`Reporting Period: ${period.charAt(0).toUpperCase() + period.slice(1)}`, 14, yPos);
  yPos += 10;

  // Stats table
  autoTable(doc, {
    startY: yPos,
    head: [["Metric", "Value"]],
    body: [
      ["Total Children Registered", stats.totalChildren.toString()],
      ["Fully Immunized", stats.fullyImmunized.toString()],
      ["Vaccinated Today", stats.vaccinatedToday.toString()],
      ["Due This Week", stats.dueSoon.toString()],
      ["Defaulters", stats.defaulters.toString()],
      ["Coverage Rate", `${stats.coverageRate}%`],
      ["Dropout Rate", `${stats.dropoutRate}%`],
    ],
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 100 },
      1: { halign: "right", cellWidth: 50 },
    },
    margin: { left: 14, right: 14 },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 80;
  yPos += 15;

  // Age Distribution
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Age Distribution", 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Age Group", "Children", "Percentage"]],
    body: Object.entries(ageDistribution).map(([group, count]) => {
      const total = Object.values(ageDistribution).reduce((a, b) => a + b, 0);
      const percent = total > 0 ? Math.round((count / total) * 100) : 0;
      return [group, count.toString(), `${percent}%`];
    }),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, 1);
  
  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const periodSlug = options.periodLabel ? `_${sanitizeFilename(options.periodLabel)}` : '';
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Summary_Report${periodSlug}_${dateSlug}.pdf`);
}

export function exportDetailedReport(
  records: Array<{
    date: string;
    childName: string;
    regNo: string;
    vaccine: string;
    batchNumber: string;
    status: string;
  }>,
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  let yPos = addHeader(doc, "Detailed Vaccination Records", options);

  doc.setFontSize(11);
  doc.setTextColor(...GHS_DARK);
  doc.text(`Total Records: ${records.length}`, 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Date", "Reg No.", "Child Name", "Vaccine", "Batch No.", "Status"]],
    body: records.map((r) => [
      formatDateDDMMYYYY(r.date),
      r.regNo,
      r.childName,
      r.vaccine,
      r.batchNumber,
      r.status,
    ]),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 8,
      cellPadding: 4,
    },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 30 },
      2: { cellWidth: 40 },
      3: { cellWidth: 50 },
      4: { cellWidth: 25 },
      5: { cellWidth: 20 },
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber);
    },
  });

  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const periodSlug = options.periodLabel ? `_${sanitizeFilename(options.periodLabel)}` : '';
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Detailed_Report${periodSlug}_${dateSlug}.pdf`);
}

export function exportVaccineCoverageReport(
  vaccineCoverage: Record<string, { given: number; pending: number; overdue: number }>,
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  let yPos = addHeader(doc, "Vaccine Coverage Report", options);

  autoTable(doc, {
    startY: yPos,
    head: [["Vaccine Type", "Given", "Pending", "Overdue", "Total", "Coverage %"]],
    body: Object.entries(vaccineCoverage).map(([type, data]) => {
      const total = data.given + data.pending + data.overdue;
      const coverage = total > 0 ? Math.round((data.given / total) * 100) : 0;
      return [
        type,
        data.given.toString(),
        data.pending.toString(),
        data.overdue.toString(),
        total.toString(),
        `${coverage}%`,
      ];
    }),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 45 },
      1: { halign: "center", cellWidth: 25 },
      2: { halign: "center", cellWidth: 25 },
      3: { halign: "center", cellWidth: 25 },
      4: { halign: "center", cellWidth: 25 },
      5: { halign: "center", cellWidth: 30, fontStyle: "bold" },
    },
    margin: { left: 14, right: 14 },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 100;
  yPos += 15;

  // Legend
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Legend:", 14, yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  // Given indicator
  doc.setFillColor(0, 100, 0);
  doc.circle(18, yPos - 1, 2, "F");
  doc.text("Given - Vaccines successfully administered", 24, yPos);
  yPos += 6;

  // Pending indicator
  doc.setFillColor(245, 158, 11);
  doc.circle(18, yPos - 1, 2, "F");
  doc.text("Pending - Vaccines not yet due or awaiting administration", 24, yPos);
  yPos += 6;

  // Overdue indicator
  doc.setFillColor(206, 17, 38);
  doc.circle(18, yPos - 1, 2, "F");
  doc.text("Overdue - Vaccines past due date requiring follow-up", 24, yPos);

  addFooter(doc, 1);
  
  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const periodSlug = options.periodLabel ? `_${sanitizeFilename(options.periodLabel)}` : '';
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Vaccine_Coverage${periodSlug}_${dateSlug}.pdf`);
}

export function exportDefaultersReport(
  defaulters: Defaulter[],
  options: PDFOptions = {}
) {
  const doc = new jsPDF("landscape");
  let yPos = addHeader(doc, "Defaulters Report", options);

  // Summary stats
  const critical = defaulters.filter((d) => d.daysOverdue > 30).length;
  const moderate = defaulters.filter((d) => d.daysOverdue >= 14 && d.daysOverdue <= 30).length;
  const recent = defaulters.filter((d) => d.daysOverdue < 14).length;

  doc.setFontSize(10);
  doc.setTextColor(...GHS_DARK);
  doc.text(`Total Defaulters: ${defaulters.length}`, 14, yPos);
  
  doc.setTextColor(206, 17, 38);
  doc.text(`Critical (>30 days): ${critical}`, 80, yPos);
  
  doc.setTextColor(245, 158, 11);
  doc.text(`Moderate (14-30 days): ${moderate}`, 150, yPos);
  
  doc.setTextColor(59, 130, 246);
  doc.text(`Recent (<14 days): ${recent}`, 230, yPos);
  
  yPos += 10;

  autoTable(doc, {
    startY: yPos,
    head: [["#", "Child Name", "Caregiver", "Contact", "Community", "Missed Vaccines", "Due Date", "Days Overdue"]],
    body: defaulters.map((d, idx) => [
      (idx + 1).toString(),
      d.child.name,
      d.child.motherName,
      d.child.telephoneAddress || "N/A",
      d.child.community || "N/A",
      d.missedVaccines.slice(0, 2).join(", ") + (d.missedVaccines.length > 2 ? ` +${d.missedVaccines.length - 2}` : ""),
      formatDateDDMMYYYY(d.dueDate),
      d.daysOverdue.toString(),
    ]),
    headStyles: {
      fillColor: GHS_RED,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [255, 235, 238],
    },
    styles: {
      fontSize: 8,
      cellPadding: 4,
    },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      1: { cellWidth: 35 },
      2: { cellWidth: 35 },
      3: { cellWidth: 35 },
      4: { cellWidth: 30 },
      5: { cellWidth: 60 },
      6: { cellWidth: 25 },
      7: { cellWidth: 25, halign: "center" },
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber);
    },
    // Color code rows by severity
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 7) {
        const daysOverdue = parseInt(data.cell.raw as string);
        if (daysOverdue > 30) {
          data.cell.styles.textColor = [206, 17, 38];
          data.cell.styles.fontStyle = "bold";
        } else if (daysOverdue >= 14) {
          data.cell.styles.textColor = [245, 158, 11];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });

  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const periodSlug = options.periodLabel ? `_${sanitizeFilename(options.periodLabel)}` : '';
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Defaulters_Report${periodSlug}_${dateSlug}.pdf`);
}

export function exportChildrenRegister(
  children: Child[],
  options: PDFOptions = {}
) {
  const doc = new jsPDF("landscape");
  let yPos = addHeader(doc, "Child Health Register", options);

  doc.setFontSize(10);
  doc.setTextColor(...GHS_DARK);
  doc.text(`Total Children (0-59 months): ${children.length}`, 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Reg No.", "Name", "DOB", "Age", "Sex", "Caregiver", "Contact", "Community", "Vaccines"]],
    body: children.map((child) => {
      const birthDate = new Date(child.dateOfBirth);
      const today = new Date();
      const months = (today.getFullYear() - birthDate.getFullYear()) * 12 + (today.getMonth() - birthDate.getMonth());
      const scheduleRows = buildCompleteScheduleRows(child);
      const completed = scheduleRows.filter((v) => v.status === "completed").length;
      const total = scheduleRows.length;
      
      return [
        child.regNo,
        child.name,
        formatDateDDMMYYYY(child.dateOfBirth),
        `${months}m`,
        child.sex,
        child.motherName,
        child.telephoneAddress || "N/A",
        child.community || "N/A",
        `${completed}/${total}`,
      ];
    }),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber);
    },
  });

  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Children_Register_${dateSlug}.pdf`);
}

// Export individual child's vaccine history with administered vaccines
export function exportVaccineHistory(
  child: Child,
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  let yPos = addHeader(doc, "Vaccination History Report", options);

  // Child info
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_DARK);
  doc.text("Child Information", 14, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const birthDate = new Date(child.dateOfBirth);
  const today = new Date();
  const months = (today.getFullYear() - birthDate.getFullYear()) * 12 + (today.getMonth() - birthDate.getMonth());
  
  const childInfo = [
    ["Registration No:", child.regNo],
    ["Name:", child.name],
    ["Date of Birth:", formatDateDDMMYYYY(child.dateOfBirth)],
    ["Age:", `${months} months`],
    ["Sex:", child.sex],
    ["Caregiver:", child.motherName],
    ["Contact:", child.telephoneAddress || "N/A"],
    ["Community:", child.community || "N/A"],
  ];

  childInfo.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 14, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(value, 55, yPos);
    yPos += 6;
  });

  yPos += 10;

  // Complete schedule: every vaccine from birth → 59 months
  const historyRows = buildCompleteScheduleRows(child);
  const givenCount = historyRows.filter(v => v.status === "completed").length;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Immunization Schedule (${givenCount} of ${historyRows.length} given)`, 14, yPos);
  yPos += 8;

  {
    autoTable(doc, {
      startY: yPos,
      head: [["#", "Vaccine", "Date Given", "Status", "Batch Number", "Administered By"]],
      body: historyRows.map((v, idx) => [
        (idx + 1).toString(),
        v.name,
        v.givenDate ? formatDateDDMMYYYY(v.givenDate) : "—",
        v.status === "completed" ? "GIVEN" : v.status === "overdue" ? "OVERDUE" : "PENDING",
        v.batchNumber || "—",
        v.administeredBy || "—",
      ]),
      headStyles: {
        fillColor: GHS_GREEN,
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 9,
      },
      alternateRowStyles: {
        fillColor: [232, 245, 232],
      },
      styles: {
        fontSize: 8,
        cellPadding: 3,
      },
      columnStyles: {
        0: { cellWidth: 8, halign: "center" },
        1: { cellWidth: 55 },
        2: { cellWidth: 25, halign: "center" },
        3: { cellWidth: 22, halign: "center", fontStyle: "bold" },
        4: { cellWidth: 28 },
        5: { cellWidth: 34 },
      },
      margin: { left: 14, right: 14 },
      showHead: "everyPage",
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 3) {
          const raw = String(data.cell.raw);
          data.cell.styles.textColor =
            raw === "GIVEN" ? [0, 128, 0] : raw === "OVERDUE" ? [206, 17, 38] : [130, 130, 130];
        }
      },
    });

    yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 50;
  }

  // Summary stats
  yPos += 15;
  const completed = givenCount;
  const pending = historyRows.filter(v => v.status === "pending").length;
  const overdue = historyRows.filter(v => v.status === "overdue").length;
  const total = historyRows.length;
  const progress = total > 0 ? Math.round((completed / total) * 100) : 0;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Vaccination Summary", 14, yPos);
  yPos += 8;

  // Progress bar
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(14, yPos, 100, 8, 2, 2, "F");
  doc.setFillColor(...GHS_GREEN);
  doc.roundedRect(14, yPos, progress, 8, 2, 2, "F");
  doc.setFontSize(9);
  doc.setTextColor(...GHS_DARK);
  doc.text(`${progress}% Complete`, 120, yPos + 6);
  yPos += 15;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setFillColor(...GHS_GREEN);
  doc.circle(18, yPos - 1, 2, "F");
  doc.text(`Completed: ${completed}`, 24, yPos);
  
  doc.setFillColor(245, 158, 11);
  doc.circle(70, yPos - 1, 2, "F");
  doc.text(`Pending: ${pending}`, 76, yPos);
  
  doc.setFillColor(...GHS_RED);
  doc.circle(120, yPos - 1, 2, "F");
  doc.text(`Overdue: ${overdue}`, 126, yPos);

  addFooter(doc, 1);
  
  const facilitySlug = sanitizeFilename(options.facilityName || 'GHS');
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Vaccine_History_${child.regNo}_${dateSlug}.pdf`);
}

export async function exportImmunizationCard(
  child: Child,
  options: PDFOptions = {}
) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4", // Single A4 sheet
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const facilityName = options.facilityName || FACILITY_CONFIG.name;
  const district = FACILITY_CONFIG.district || "District not provided";
  const region = FACILITY_CONFIG.region || "Region not provided";

  // Load GHS logo
  const ghsLogoBase64 = await loadGHSLogoBase64();

  const scheduleRows = buildCompleteScheduleRows(child);
  const completed = scheduleRows.filter(v => v.status === "completed").length;
  const total = scheduleRows.length;
  const progress = total > 0 ? Math.round((completed / total) * 100) : 0;

  // Generate QR code with verification data
  const verificationData = {
    id: child.id,
    regNo: child.regNo,
    name: child.name,
    dob: child.dateOfBirth,
    sex: child.sex,
    facility: facilityName,
    district,
    region,
    vaccinesCompleted: completed,
    totalVaccines: total,
    generatedAt: new Date().toISOString(),
  };

  const qrCodeDataUrl = await QRCode.toDataURL(JSON.stringify(verificationData), {
    width: 300,
    margin: 1,
    errorCorrectionLevel: 'H',
    color: {
      dark: "#006400",
      light: "#ffffff",
    },
  });

  // Outer decorative border
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(2);
  doc.rect(4, 4, pageWidth - 8, pageHeight - 8, "S");

  // Inner border
  doc.setLineWidth(0.5);
  doc.rect(6.5, 6.5, pageWidth - 13, pageHeight - 13, "S");

  // Header block
  doc.setFillColor(...GHS_GREEN);
  doc.rect(6.5, 6.5, pageWidth - 13, 42, "F");

  // Gold accent stripe
  doc.setFillColor(...GHS_GOLD);
  doc.rect(6.5, 48.5, pageWidth - 13, 3, "F");

  // GHS Logo
  doc.setFillColor(255, 255, 255);
  doc.circle(pageWidth / 2, 20, 12, "F");
  doc.setDrawColor(...GHS_GOLD);
  doc.setLineWidth(0.8);
  doc.circle(pageWidth / 2, 20, 12, "S");
  if (ghsLogoBase64) {
    doc.addImage(ghsLogoBase64, "PNG", pageWidth / 2 - 10, 10, 20, 20);
  } else {
    doc.setTextColor(...GHS_GREEN);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("GHS", pageWidth / 2, 22, { align: "center" });
  }

  // Header text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("REPUBLIC OF GHANA", pageWidth / 2, 38, { align: "center" });
  doc.setFontSize(15);
  doc.text("CHILD IMMUNIZATION CERTIFICATE", pageWidth / 2, 46, { align: "center" });

  // Facility box
  let yPos = 57;
  doc.setFillColor(245, 250, 245);
  doc.roundedRect(10, yPos, pageWidth - 20, 20, 2, 2, "F");
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(0.3);
  doc.roundedRect(10, yPos, pageWidth - 20, 20, 2, 2, "S");

  doc.setTextColor(...GHS_GREEN);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text(facilityName.toUpperCase(), pageWidth / 2, yPos + 9, { align: "center" });
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(`District: ${district} | Region: ${region}`, pageWidth / 2, yPos + 15, { align: "center" });

  // Child particulars
  yPos = 83;
  const particularsHeight = 50;
  doc.setFillColor(250, 252, 250);
  doc.roundedRect(10, yPos, pageWidth - 20, particularsHeight, 2, 2, "F");
  doc.setDrawColor(...GHS_GREEN);
  doc.roundedRect(10, yPos, pageWidth - 20, particularsHeight, 2, 2, "S");

  doc.setFillColor(...GHS_GREEN);
  doc.rect(10, yPos, pageWidth - 20, 8, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("CHILD PARTICULARS", pageWidth / 2, yPos + 5.5, { align: "center" });

  // QR code
  doc.addImage(qrCodeDataUrl, "PNG", pageWidth - 48, yPos + 11, 32, 32);

  // Details
  const details: [string, string][] = [
    ["Registration No:", child.regNo],
    ["Full Name:", child.name],
    ["Date of Birth:", formatDateDDMMYYYY(child.dateOfBirth)],
    ["Sex:", child.sex],
    ["Caregiver:", child.motherName],
    ["Contact:", child.telephoneAddress || "N/A"],
  ];

  let detailY = yPos + 15;
  doc.setFontSize(9);
  details.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100, 100, 100);
    doc.text(label, 16, detailY);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GHS_DARK);
    doc.text(String(value).substring(0, 34), 52, detailY);
    detailY += 6.2;
  });

  // Immunization record header bar
  yPos = 139;
  doc.setFillColor(...GHS_GREEN);
  doc.rect(10, yPos, pageWidth - 20, 9, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("IMMUNIZATION RECORD", pageWidth / 2, yPos + 6, { align: "center" });
  yPos += 12;

  const shortDate = (d?: string) =>
    d ? new Date(d).toLocaleDateString("en-GB", { day: "2-digit", month: "2-digit", year: "2-digit" }) : "-";
  const statusLabel = (s: string) =>
    s === "completed" ? "GIVEN" : s === "overdue" ? "OVERDUE" : "PENDING";

  // Two vaccines per printed row so the full schedule fits one A4 sheet
  const half = Math.ceil(scheduleRows.length / 2);
  const leftCol = scheduleRows.slice(0, half);
  const rightCol = scheduleRows.slice(half);
  const cardBody = leftCol.map((v, i) => {
    const r = rightCol[i];
    return [
      v.name.split(" at")[0].substring(0, 22),
      shortDate(v.dueDate),
      shortDate(v.givenDate),
      statusLabel(v.status),
      r ? r.name.split(" at")[0].substring(0, 22) : "",
      r ? shortDate(r.dueDate) : "",
      r ? shortDate(r.givenDate) : "",
      r ? statusLabel(r.status) : "",
    ];
  });

  autoTable(doc, {
    startY: yPos,
    head: [["Vaccine", "Due", "Given", "Status", "Vaccine", "Due", "Given", "Status"]],
    body: cardBody,
    theme: "grid",
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontSize: 7,
      cellPadding: 1.2,
      fontStyle: "bold",
      halign: "center",
      lineColor: [230, 230, 230],
    },
    bodyStyles: {
      fontSize: 6.4,
      cellPadding: 1,
      lineColor: [230, 230, 230],
      lineWidth: 0.1,
    },
    alternateRowStyles: {
      fillColor: [248, 252, 248],
    },
    columnStyles: {
      0: { cellWidth: 40, halign: "left" },
      1: { cellWidth: 17, halign: "center" },
      2: { cellWidth: 17, halign: "center" },
      3: { cellWidth: 21, halign: "center", fontStyle: "bold" },
      4: { cellWidth: 40, halign: "left" },
      5: { cellWidth: 17, halign: "center" },
      6: { cellWidth: 17, halign: "center" },
      7: { cellWidth: 21, halign: "center", fontStyle: "bold" },
    },
    margin: { left: 10, right: 10 },
    tableWidth: pageWidth - 20,
    didParseCell: (data) => {
      if (data.section === "body" && (data.column.index === 3 || data.column.index === 7)) {
        if (String(data.cell.raw) === "GIVEN") {
          data.cell.styles.textColor = [0, 128, 0];
        } else if (String(data.cell.raw) === "OVERDUE") {
          data.cell.styles.textColor = [206, 17, 38];
        } else {
          data.cell.styles.textColor = [150, 150, 150];
        }
      }
    },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 90;
  yPos += 5;

  // Progress section with visual bar
  doc.setFillColor(248, 252, 248);
  doc.roundedRect(10, yPos, pageWidth - 20, 18, 2, 2, "F");
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(0.3);
  doc.roundedRect(10, yPos, pageWidth - 20, 18, 2, 2, "S");

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_DARK);
  doc.text("VACCINATION PROGRESS", 16, yPos + 6.5);

  const barWidth = 90;
  const barX = 16;
  const barY = yPos + 10.5;
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(barX, barY, barWidth, 4, 2, 2, "F");

  if (progress > 0) {
    doc.setFillColor(progress >= 100 ? 0 : 34, progress >= 100 ? 150 : 139, progress >= 100 ? 0 : 34);
    doc.roundedRect(barX, barY, (progress / 100) * barWidth, 4, 2, 2, "F");
  }

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(progress >= 100 ? 0 : 34, progress >= 100 ? 150 : 139, progress >= 100 ? 0 : 34);
  doc.text(`${progress}%`, barX + barWidth + 6, barY + 4);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`${completed} of ${total} vaccines completed`, pageWidth - 16, barY + 3, { align: "right" });

  // Footer section
  yPos = pageHeight - 26;
  doc.setFillColor(...GHS_GOLD);
  doc.rect(10, yPos, pageWidth - 20, 1, "F");
  yPos += 5;

  doc.setFontSize(7.5);
  doc.setTextColor(...GHS_DARK);
  doc.setFont("helvetica", "italic");
  doc.text("This is an official health document. Please present at every clinic visit.", pageWidth / 2, yPos, { align: "center" });
  yPos += 4;
  doc.text("Keep this card safe. Report loss immediately to your health facility.", pageWidth / 2, yPos, { align: "center" });

  // Bottom bar with Ghana colours
  doc.setFillColor(206, 17, 38);
  doc.rect(6.5, pageHeight - 13, (pageWidth - 13) / 3, 3.5, "F");
  doc.setFillColor(255, 215, 0);
  doc.rect(6.5 + (pageWidth - 13) / 3, pageHeight - 13, (pageWidth - 13) / 3, 3.5, "F");
  doc.setFillColor(0, 100, 0);
  doc.rect(6.5 + 2 * (pageWidth - 13) / 3, pageHeight - 13, (pageWidth - 13) / 3, 3.5, "F");

  // Card ID footer
  doc.setFontSize(6.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(
    `Card ID: ${child.regNo} | Issued: ${formatDateDDMMYYYY(new Date())} | Ghana Health Service - EPI Program`,
    pageWidth / 2,
    pageHeight - 7.5,
    { align: "center" }
  );

  const facilitySlug = sanitizeFilename(facilityName);
  doc.save(`${facilitySlug}_Immunization_Certificate_${child.regNo}_${child.name.replace(/\s+/g, "_")}.pdf`);
}


// Export outreach session report for bulk vaccination
export interface OutreachVaccinationRecord {
  childId: string;
  childName: string;
  regNo: string;
  motherName: string; // Caregiver name (legacy field name for compatibility)
  community?: string;
  vaccine: string;
  dateGiven: string;
  batchNumber: string;
  dateOfBirth?: string; // For age calculation
}

export function exportOutreachSessionReport(
  records: OutreachVaccinationRecord[],
  sessionDetails: {
    sessionId?: string;
    vaccineName: string;
    sessionDate: string;
    batchNumber: string;
    totalChildren: number;
    totalMales?: number;
    totalFemales?: number;
    outreachSite?: string;
  },
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  // Always use FIAN URBAN CHPS (never user-editable)
  const facilityName = options.facilityName || FACILITY_CONFIG.name;
  let yPos = addHeader(doc, "Outreach Session Report", options);

  // Facility Name
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_GREEN);
  doc.text(facilityName, 14, yPos);
  yPos += 10;

  // Session Summary
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_DARK);
  doc.text("Session Summary", 14, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  
  const sessionInfo: [string, string][] = [
    ["Vaccine Administered:", sessionDetails.vaccineName],
    ["Session Date:", formatDateDDMMYYYY(sessionDetails.sessionDate)],
    ["Batch Number:", sessionDetails.batchNumber],
    ["Total Children Vaccinated:", sessionDetails.totalChildren.toString()],
  ];

  // Add outreach site if available
  if (sessionDetails.outreachSite) {
    sessionInfo.push(["Outreach Site:", sessionDetails.outreachSite]);
  }

  // Add gender breakdown if available
  if (sessionDetails.totalMales !== undefined && sessionDetails.totalFemales !== undefined) {
    sessionInfo.push(["Total Males:", sessionDetails.totalMales.toString()]);
    sessionInfo.push(["Total Females:", sessionDetails.totalFemales.toString()]);
  }

  sessionInfo.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 14, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(value, 65, yPos);
    yPos += 6;
  });

  yPos += 10;

  // Vaccination Records Table
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Vaccinated Children", 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["#", "Reg No.", "Child Name", "Caregiver", "Community", "Date Given", "Batch No."]],
    body: records.map((r, idx) => [
      (idx + 1).toString(),
      r.regNo,
      r.childName,
      r.motherName,
      r.community || "N/A",
      formatDateDDMMYYYY(r.dateGiven),
      r.batchNumber,
    ]),
    headStyles: {
      fillColor: GHS_GREEN,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [232, 245, 232],
    },
    styles: {
      fontSize: 8,
      cellPadding: 4,
    },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      1: { cellWidth: 28 },
      2: { cellWidth: 35 },
      3: { cellWidth: 35 },
      4: { cellWidth: 30 },
      5: { cellWidth: 25 },
      6: { cellWidth: 25 },
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber);
    },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 80;
  yPos += 15;

  // Signature section
  if (yPos < doc.internal.pageSize.getHeight() - 60) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GHS_DARK);
    
    doc.text("Prepared By:", 14, yPos);
    doc.line(45, yPos, 100, yPos);
    
    doc.text("Signature:", 110, yPos);
    doc.line(135, yPos, 180, yPos);
    
    yPos += 10;
    
    doc.text("Date:", 14, yPos);
    doc.line(30, yPos, 70, yPos);
    
    doc.text("Facility Stamp:", 110, yPos);
    doc.setDrawColor(...GHS_DARK);
    doc.setLineDashPattern([1, 1], 0);
    doc.rect(150, yPos - 15, 35, 25, "S");
  }

  const facilitySlug = sanitizeFilename(facilityName);
  const vaccineSlug = sanitizeFilename(sessionDetails.vaccineName);
  const dateSlug = new Date(sessionDetails.sessionDate).toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Outreach_Session_${vaccineSlug}_${dateSlug}.pdf`);
}

// Export consolidated report combining all report types for a date range
export function exportConsolidatedReport(
  data: {
    stats: DashboardStats;
    ageDistribution: Record<string, number>;
    detailedRecords: Array<{
      date: string;
      childName: string;
      regNo: string;
      vaccine: string;
      batchNumber: string;
      status: string;
    }>;
    vaccineCoverage: Record<string, { given: number; pending: number; overdue: number; eligible?: number }>;
    defaulters: Defaulter[];
  },
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  // Always use FIAN URBAN CHPS (never user-editable)
  const facilityName = options.facilityName || FACILITY_CONFIG.name;
  const { periodLabel } = options;
  let currentPage = 1;
  
  // ============ Page 1: Summary Report ============
  let yPos = addHeader(doc, "Consolidated Report - Summary", options);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GHS_DARK);
  doc.text(`Reporting Period: ${periodLabel || 'All Time'}`, 14, yPos);
  yPos += 10;

  // Stats table
  autoTable(doc, {
    startY: yPos,
    head: [["Metric", "Value"]],
    body: [
      ["Total Children Registered", data.stats.totalChildren.toString()],
      ["Fully Immunized", data.stats.fullyImmunized.toString()],
      ["Vaccinated Today", data.stats.vaccinatedToday.toString()],
      ["Due This Week", data.stats.dueSoon.toString()],
      ["Defaulters", data.stats.defaulters.toString()],
      ["Coverage Rate", `${data.stats.coverageRate}%`],
      ["Dropout Rate", `${data.stats.dropoutRate}%`],
    ],
    headStyles: { fillColor: GHS_GREEN, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [232, 245, 232] },
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 100 }, 1: { halign: "right", cellWidth: 50 } },
    margin: { left: 14, right: 14 },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 80;
  yPos += 15;

  // Age Distribution
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Age Distribution", 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Age Group", "Children", "Percentage"]],
    body: Object.entries(data.ageDistribution).map(([group, count]) => {
      const total = Object.values(data.ageDistribution).reduce((a, b) => a + b, 0);
      const percent = total > 0 ? Math.round((count / total) * 100) : 0;
      return [group, count.toString(), `${percent}%`];
    }),
    headStyles: { fillColor: GHS_GREEN, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [232, 245, 232] },
    styles: { fontSize: 10, cellPadding: 5 },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, currentPage);
  currentPage++;

  // ============ Page 2: Vaccine Coverage ============
  doc.addPage();
  yPos = addHeader(doc, "Consolidated Report - Vaccine Coverage", options);

  autoTable(doc, {
    startY: yPos,
    head: [["Schedule", "Eligible", "Given", "Pending", "Overdue", "Coverage %"]],
    body: Object.entries(data.vaccineCoverage).map(([type, coverage]) => {
      const eligible = coverage.eligible || (coverage.given + coverage.pending + coverage.overdue);
      const coveragePercent = eligible > 0 ? Math.round((coverage.given / eligible) * 100) : 0;
      return [type, eligible.toString(), coverage.given.toString(), coverage.pending.toString(), coverage.overdue.toString(), `${coveragePercent}%`];
    }),
    headStyles: { fillColor: GHS_GREEN, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [232, 245, 232] },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 40 }, 5: { fontStyle: "bold", halign: "center" } },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc, currentPage);
  currentPage++;

  // ============ Page 3+: Detailed Records ============
  doc.addPage();
  yPos = addHeader(doc, "Consolidated Report - Detailed Records", options);

  doc.setFontSize(11);
  doc.setTextColor(...GHS_DARK);
  doc.text(`Total Records: ${data.detailedRecords.length}`, 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [["Date", "Reg No.", "Child Name", "Vaccine", "Batch No.", "Status"]],
    body: data.detailedRecords.slice(0, 100).map((r) => [
      formatDateDDMMYYYY(r.date),
      r.regNo,
      r.childName,
      r.vaccine,
      r.batchNumber,
      r.status,
    ]),
    headStyles: { fillColor: GHS_GREEN, textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 },
    alternateRowStyles: { fillColor: [232, 245, 232] },
    styles: { fontSize: 8, cellPadding: 4 },
    margin: { left: 14, right: 14 },
    didDrawPage: (pageData) => { addFooter(doc, currentPage + pageData.pageNumber - 1); },
  });

  // ============ Defaulters Page ============
  if (data.defaulters.length > 0) {
    doc.addPage();
    yPos = addHeader(doc, "Consolidated Report - Defaulters", options);

    const critical = data.defaulters.filter((d) => d.daysOverdue > 30).length;
    const moderate = data.defaulters.filter((d) => d.daysOverdue >= 14 && d.daysOverdue <= 30).length;
    const recent = data.defaulters.filter((d) => d.daysOverdue < 14).length;

    doc.setFontSize(10);
    doc.setTextColor(...GHS_DARK);
    doc.text(`Total Defaulters: ${data.defaulters.length}  |  Critical (>30d): ${critical}  |  Moderate (14-30d): ${moderate}  |  Recent (<14d): ${recent}`, 14, yPos);
    yPos += 10;

    autoTable(doc, {
      startY: yPos,
      head: [["#", "Child Name", "Caregiver", "Missed Vaccines", "Due Date", "Days Overdue"]],
      body: data.defaulters.slice(0, 50).map((d, idx) => [
        (idx + 1).toString(),
        d.child.name,
        d.child.motherName,
        d.missedVaccines.slice(0, 2).join(", ") + (d.missedVaccines.length > 2 ? ` +${d.missedVaccines.length - 2}` : ""),
        formatDateDDMMYYYY(d.dueDate),
        d.daysOverdue.toString(),
      ]),
      headStyles: { fillColor: GHS_RED, textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 },
      alternateRowStyles: { fillColor: [255, 235, 238] },
      styles: { fontSize: 8, cellPadding: 4 },
      margin: { left: 14, right: 14 },
      didDrawPage: (pageData) => { addFooter(doc, pageData.pageNumber); },
    });
  }

  const facilitySlug = sanitizeFilename(facilityName);
  const periodSlug = periodLabel ? `_${sanitizeFilename(periodLabel)}` : '';
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Consolidated_Report${periodSlug}_${dateSlug}.pdf`);
}

// Export month comparison report
export function exportMonthComparisonReport(
  comparisonData: {
    month1: { periodLabel: string; uniqueChildren: number; totalVaccinations: number; defaulters: number };
    month2: { periodLabel: string; uniqueChildren: number; totalVaccinations: number; defaulters: number };
  },
  options: PDFOptions = {}
) {
  const doc = new jsPDF();
  // Always use FIAN URBAN CHPS (never user-editable)
  const facilityName = options.facilityName || FACILITY_CONFIG.name;
  
  const yPosStart = addHeader(doc, "Month-to-Month Comparison Report", {
    ...options,
    periodLabel: `${comparisonData.month1.periodLabel} vs ${comparisonData.month2.periodLabel}`
  });
  let yPos = yPosStart;

  // Comparison header
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_DARK);
  doc.text("Side-by-Side Comparison", 14, yPos);
  yPos += 10;

  const pageWidth = doc.internal.pageSize.getWidth();
  const halfWidth = (pageWidth - 42) / 2;

  // Month 1 Box
  doc.setFillColor(232, 245, 232);
  doc.roundedRect(14, yPos, halfWidth, 60, 3, 3, "F");
  doc.setDrawColor(...GHS_GREEN);
  doc.setLineWidth(0.5);
  doc.roundedRect(14, yPos, halfWidth, 60, 3, 3, "S");

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_GREEN);
  doc.text(comparisonData.month1.periodLabel, 20, yPos + 12);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GHS_DARK);
  doc.text(`Unique Children: ${comparisonData.month1.uniqueChildren}`, 20, yPos + 26);
  doc.text(`Total Vaccinations: ${comparisonData.month1.totalVaccinations}`, 20, yPos + 38);
  doc.text(`Defaulters: ${comparisonData.month1.defaulters}`, 20, yPos + 50);

  // Month 2 Box
  const month2X = 14 + halfWidth + 14;
  doc.setFillColor(232, 245, 232);
  doc.roundedRect(month2X, yPos, halfWidth, 60, 3, 3, "F");
  doc.setDrawColor(...GHS_GREEN);
  doc.roundedRect(month2X, yPos, halfWidth, 60, 3, 3, "S");

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_GREEN);
  doc.text(comparisonData.month2.periodLabel, month2X + 6, yPos + 12);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GHS_DARK);
  doc.text(`Unique Children: ${comparisonData.month2.uniqueChildren}`, month2X + 6, yPos + 26);
  doc.text(`Total Vaccinations: ${comparisonData.month2.totalVaccinations}`, month2X + 6, yPos + 38);
  doc.text(`Defaulters: ${comparisonData.month2.defaulters}`, month2X + 6, yPos + 50);

  yPos += 75;

  // Change Analysis Section
  doc.setFillColor(...GHS_GOLD);
  doc.rect(14, yPos, pageWidth - 28, 8, "F");
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_DARK);
  doc.text("CHANGE ANALYSIS", 18, yPos + 6);
  yPos += 15;

  const childrenDiff = comparisonData.month1.uniqueChildren - comparisonData.month2.uniqueChildren;
  const vaccDiff = comparisonData.month1.totalVaccinations - comparisonData.month2.totalVaccinations;
  const defaulterDiff = comparisonData.month1.defaulters - comparisonData.month2.defaulters;

  const changes = [
    { metric: "Children Seen", diff: childrenDiff, positive: childrenDiff > 0 },
    { metric: "Vaccinations Given", diff: vaccDiff, positive: vaccDiff > 0 },
    { metric: "Defaulters", diff: defaulterDiff, positive: defaulterDiff < 0 }, // fewer defaulters is good
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["Metric", `${comparisonData.month1.periodLabel}`, `${comparisonData.month2.periodLabel}`, "Change", "Trend"]],
    body: [
      ["Children Seen", comparisonData.month1.uniqueChildren.toString(), comparisonData.month2.uniqueChildren.toString(), 
       `${childrenDiff > 0 ? '+' : ''}${childrenDiff}`, childrenDiff > 0 ? "↑ Increase" : childrenDiff < 0 ? "↓ Decrease" : "→ No Change"],
      ["Vaccinations", comparisonData.month1.totalVaccinations.toString(), comparisonData.month2.totalVaccinations.toString(),
       `${vaccDiff > 0 ? '+' : ''}${vaccDiff}`, vaccDiff > 0 ? "↑ Increase" : vaccDiff < 0 ? "↓ Decrease" : "→ No Change"],
      ["Defaulters", comparisonData.month1.defaulters.toString(), comparisonData.month2.defaulters.toString(),
       `${defaulterDiff > 0 ? '+' : ''}${defaulterDiff}`, defaulterDiff < 0 ? "↑ Improved" : defaulterDiff > 0 ? "↓ Worsened" : "→ No Change"],
    ],
    headStyles: { fillColor: GHS_GREEN, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [232, 245, 232] },
    styles: { fontSize: 10, cellPadding: 6 },
    columnStyles: { 
      0: { fontStyle: "bold" },
      3: { halign: "center", fontStyle: "bold" },
      4: { halign: "center" }
    },
    margin: { left: 14, right: 14 },
    didParseCell: (cellData) => {
      if (cellData.section === "body" && cellData.column.index === 4) {
        const text = cellData.cell.raw as string;
        if (text.includes("Increase") || text.includes("Improved")) {
          cellData.cell.styles.textColor = [0, 128, 0];
        } else if (text.includes("Decrease") || text.includes("Worsened")) {
          cellData.cell.styles.textColor = [206, 17, 38];
        }
      }
      if (cellData.section === "body" && cellData.column.index === 3) {
        const text = cellData.cell.raw as string;
        if (text.startsWith('+')) {
          cellData.cell.styles.textColor = [0, 128, 0];
        } else if (text.startsWith('-')) {
          cellData.cell.styles.textColor = [206, 17, 38];
        }
      }
    },
  });

  yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 60;
  yPos += 20;

  // Summary recommendation
  doc.setFillColor(250, 250, 240);
  doc.roundedRect(14, yPos, pageWidth - 28, 35, 3, 3, "F");
  doc.setDrawColor(...GHS_GOLD);
  doc.roundedRect(14, yPos, pageWidth - 28, 35, 3, 3, "S");

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GHS_DARK);
  doc.text("Summary:", 20, yPos + 10);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const summaryText = `Comparing ${comparisonData.month1.periodLabel} to ${comparisonData.month2.periodLabel}: ` +
    `${Math.abs(childrenDiff)} ${childrenDiff >= 0 ? 'more' : 'fewer'} children seen, ` +
    `${Math.abs(vaccDiff)} ${vaccDiff >= 0 ? 'more' : 'fewer'} vaccinations administered, ` +
    `${Math.abs(defaulterDiff)} ${defaulterDiff <= 0 ? 'fewer' : 'more'} defaulters.`;
  
  const splitText = doc.splitTextToSize(summaryText, pageWidth - 50);
  doc.text(splitText, 20, yPos + 20);

  addFooter(doc, 1);

  const facilitySlug = sanitizeFilename(facilityName);
  const month1Slug = sanitizeFilename(comparisonData.month1.periodLabel);
  const month2Slug = sanitizeFilename(comparisonData.month2.periodLabel);
  const dateSlug = new Date().toISOString().split("T")[0];
  doc.save(`${facilitySlug}_Comparison_${month1Slug}_vs_${month2Slug}_${dateSlug}.pdf`);
}
