import { writeFileSync } from "fs";
import jsPDF from "jspdf";
(jsPDF as any).API.save = function (name: string) { writeFileSync("/tmp/epitest/" + name, Buffer.from(this.output("arraybuffer") as ArrayBuffer)); return this; };
const { exportDefaulterTracingWorksheet, exportAppointmentSlip, exportMonthlyEpiReturn } = await import("./src/lib/epiReports.ts");
const today = new Date();
const child: any = { id: "1", userId: "u", regNo: "IMU-20250101-U001-AB12", name: "Ama Mensah", dateOfBirth: "2024-09-01", sex: "Female", motherName: "Akua Mensah", telephoneAddress: "0244000000", community: "Fian", registeredAt: today.toISOString(), vaccines: [{ name: "BCG at Birth", dueDate: "2024-09-01", givenDate: today.toISOString().split("T")[0], status: "completed" }, { name: "OPV0 at Birth", dueDate: "2024-09-01", givenDate: today.toISOString().split("T")[0], status: "completed" }] };
exportAppointmentSlip(child);
exportDefaulterTracingWorksheet([{ child, missedVaccines: ["Penta1 at 6 weeks", "PCV1 at 6 weeks"], dueDate: "2024-10-15", daysOverdue: 120 }]);
exportMonthlyEpiReturn([child], today.getFullYear(), today.getMonth());
console.log("ok");
